/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Comment {
    id: bigint;
    content: string;
    authorName?: string;
    likedBy: Array<Principal>;
    author: Principal;
    timestamp: Time;
    authorProfilePicture?: Uint8Array;
    isLikedByCurrentUser: boolean;
    postId: bigint;
}
export type Username = string;
export type Time = bigint;
export interface UserProfileInput {
    bio?: string;
    username: Username;
    name?: string;
    profilePictureBlob?: Uint8Array;
}
export interface UserProfile {
    bio?: string;
    username: Username;
    displayName: string;
    followersCount: bigint;
    name?: string;
    createdAt: Time;
    updatedAt: Time;
    followingCount: bigint;
    isFollowedByCurrentUser: boolean;
    postsCount: bigint;
}
export interface Post {
    id: bigint;
    content: string;
    authorName?: string;
    likedBy: Array<Principal>;
    author: Principal;
    timestamp: Time;
    authorProfilePicture?: Uint8Array;
    isLikedByCurrentUser: boolean;
}
export interface backendInterface {
    checkUsernameAvailability(username: string): Promise<boolean>;
    createComment(postId: bigint, content: string): Promise<void>;
    createPost(content: string): Promise<void>;
    deleteComment(commentId: bigint): Promise<void>;
    deletePost(id: bigint): Promise<void>;
    followUser(userToFollow: Principal): Promise<void>;
    getAllPosts(): Promise<Array<Post>>;
    getFollowersList(user: Principal): Promise<Array<Principal>>;
    getFollowingFeed(): Promise<Array<Post>>;
    getFollowingList(user: Principal): Promise<Array<Principal>>;
    getPost(id: bigint): Promise<Post | null>;
    getPostComments(postId: bigint): Promise<Array<Comment>>;
    getProfilePictureBlob(userPrincipal: Principal): Promise<Uint8Array | null>;
    getUserByUsername(username: string): Promise<UserProfile | null>;
    getUserPrincipalByUsername(username: string): Promise<Principal | null>;
    getUserProfile(): Promise<UserProfile | null>;
    getUserProfileWithStats(user: Principal): Promise<UserProfile | null>;
    likeComment(commentId: bigint): Promise<void>;
    likePost(postId: bigint): Promise<void>;
    needsProfileSetup(): Promise<boolean>;
    saveUserProfile(profileInput: UserProfileInput): Promise<void>;
    unfollowUser(userToUnfollow: Principal): Promise<void>;
    unlikeComment(commentId: bigint): Promise<void>;
    unlikePost(postId: bigint): Promise<void>;
}
import type { Comment as _Comment, Post as _Post, Time as _Time, UserProfile as _UserProfile, UserProfileInput as _UserProfileInput, Username as _Username } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async checkUsernameAvailability(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkUsernameAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkUsernameAvailability(arg0);
            return result;
        }
    }
    async createComment(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createComment(arg0, arg1);
            return result;
        }
    }
    async createPost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0);
            return result;
        }
    }
    async deleteComment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async deletePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async followUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getAllPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPosts();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPosts();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowersList(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowersList(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowersList(arg0);
            return result;
        }
    }
    async getFollowingFeed(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowingFeed();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowingFeed();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowingList(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowingList(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowingList(arg0);
            return result;
        }
    }
    async getPost(arg0: bigint): Promise<Post | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostComments(arg0: bigint): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostComments(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostComments(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfilePictureBlob(arg0: Principal): Promise<Uint8Array | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfilePictureBlob(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfilePictureBlob(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserByUsername(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByUsername(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByUsername(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPrincipalByUsername(arg0: string): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPrincipalByUsername(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPrincipalByUsername(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfileWithStats(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfileWithStats(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfileWithStats(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async likeComment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeComment(arg0);
            return result;
        }
    }
    async likePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async needsProfileSetup(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.needsProfileSetup();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.needsProfileSetup();
            return result;
        }
    }
    async saveUserProfile(arg0: UserProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserProfile(to_candid_UserProfileInput_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserProfile(to_candid_UserProfileInput_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async unfollowUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
    async unlikeComment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikeComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikeComment(arg0);
            return result;
        }
    }
    async unlikePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikePost(arg0);
            return result;
        }
    }
}
function from_candid_Comment_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Comment): Comment {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Post_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Post {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Post]): Post | null {
    return value.length === 0 ? null : from_candid_Post_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: [] | [string];
    username: _Username;
    displayName: string;
    followersCount: bigint;
    name: [] | [string];
    createdAt: _Time;
    updatedAt: _Time;
    followingCount: bigint;
    isFollowedByCurrentUser: boolean;
    postsCount: bigint;
}): {
    bio?: string;
    username: Username;
    displayName: string;
    followersCount: bigint;
    name?: string;
    createdAt: Time;
    updatedAt: Time;
    followingCount: bigint;
    isFollowedByCurrentUser: boolean;
    postsCount: bigint;
} {
    return {
        bio: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.bio)),
        username: value.username,
        displayName: value.displayName,
        followersCount: value.followersCount,
        name: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.name)),
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        followingCount: value.followingCount,
        isFollowedByCurrentUser: value.isFollowedByCurrentUser,
        postsCount: value.postsCount
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    authorName: [] | [string];
    likedBy: Array<Principal>;
    author: Principal;
    timestamp: _Time;
    authorProfilePicture: [] | [Uint8Array];
    isLikedByCurrentUser: boolean;
}): {
    id: bigint;
    content: string;
    authorName?: string;
    likedBy: Array<Principal>;
    author: Principal;
    timestamp: Time;
    authorProfilePicture?: Uint8Array;
    isLikedByCurrentUser: boolean;
} {
    return {
        id: value.id,
        content: value.content,
        authorName: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.authorName)),
        likedBy: value.likedBy,
        author: value.author,
        timestamp: value.timestamp,
        authorProfilePicture: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.authorProfilePicture)),
        isLikedByCurrentUser: value.isLikedByCurrentUser
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    authorName: [] | [string];
    likedBy: Array<Principal>;
    author: Principal;
    timestamp: _Time;
    authorProfilePicture: [] | [Uint8Array];
    isLikedByCurrentUser: boolean;
    postId: bigint;
}): {
    id: bigint;
    content: string;
    authorName?: string;
    likedBy: Array<Principal>;
    author: Principal;
    timestamp: Time;
    authorProfilePicture?: Uint8Array;
    isLikedByCurrentUser: boolean;
    postId: bigint;
} {
    return {
        id: value.id,
        content: value.content,
        authorName: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.authorName)),
        likedBy: value.likedBy,
        author: value.author,
        timestamp: value.timestamp,
        authorProfilePicture: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.authorProfilePicture)),
        isLikedByCurrentUser: value.isLikedByCurrentUser,
        postId: value.postId
    };
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Array<Post> {
    return value.map((x)=>from_candid_Post_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Comment>): Array<Comment> {
    return value.map((x)=>from_candid_Comment_n8(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfileInput_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfileInput): _UserProfileInput {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio?: string;
    username: Username;
    name?: string;
    profilePictureBlob?: Uint8Array;
}): {
    bio: [] | [string];
    username: _Username;
    name: [] | [string];
    profilePictureBlob: [] | [Uint8Array];
} {
    return {
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        username: value.username,
        name: value.name ? candid_some(value.name) : candid_none(),
        profilePictureBlob: value.profilePictureBlob ? candid_some(value.profilePictureBlob) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
