/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'content' : string,
  'authorName' : [] | [string],
  'likedBy' : Array<Principal>,
  'author' : Principal,
  'timestamp' : Time,
  'authorProfilePicture' : [] | [Uint8Array],
  'isLikedByCurrentUser' : boolean,
  'postId' : bigint,
}
export interface Post {
  'id' : bigint,
  'content' : string,
  'authorName' : [] | [string],
  'likedBy' : Array<Principal>,
  'author' : Principal,
  'timestamp' : Time,
  'authorProfilePicture' : [] | [Uint8Array],
  'isLikedByCurrentUser' : boolean,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : [] | [string],
  'username' : Username,
  'displayName' : string,
  'followersCount' : bigint,
  'name' : [] | [string],
  'createdAt' : Time,
  'updatedAt' : Time,
  'followingCount' : bigint,
  'isFollowedByCurrentUser' : boolean,
  'postsCount' : bigint,
}
export interface UserProfileInput {
  'bio' : [] | [string],
  'username' : Username,
  'name' : [] | [string],
  'profilePictureBlob' : [] | [Uint8Array],
}
export type Username = string;
export interface _SERVICE {
  'checkUsernameAvailability' : ActorMethod<[string], boolean>,
  'createComment' : ActorMethod<[bigint, string], undefined>,
  'createPost' : ActorMethod<[string], undefined>,
  'deleteComment' : ActorMethod<[bigint], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getFollowersList' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowingFeed' : ActorMethod<[], Array<Post>>,
  'getFollowingList' : ActorMethod<[Principal], Array<Principal>>,
  'getPost' : ActorMethod<[bigint], [] | [Post]>,
  'getPostComments' : ActorMethod<[bigint], Array<Comment>>,
  'getProfilePictureBlob' : ActorMethod<[Principal], [] | [Uint8Array]>,
  'getUserByUsername' : ActorMethod<[string], [] | [UserProfile]>,
  'getUserPrincipalByUsername' : ActorMethod<[string], [] | [Principal]>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getUserProfileWithStats' : ActorMethod<[Principal], [] | [UserProfile]>,
  'likeComment' : ActorMethod<[bigint], undefined>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'needsProfileSetup' : ActorMethod<[], boolean>,
  'saveUserProfile' : ActorMethod<[UserProfileInput], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'unlikeComment' : ActorMethod<[bigint], undefined>,
  'unlikePost' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];